language: java
services: docker
before_install: sudo service mysql stop
env:
    global:
      - PLATFORM_KEY='{"kty":"EC","kid":"918f5a24-290e-4659-9cd6-c8d95aee92c6","x":"4uV_ZyVYrm6QV1p7OPg-3BtOvoc_Pc6WGU8Rw4YT4MICzszxNqXCAoIT2iwOWiFO","y":"a_JUmWGAtF-xAlCLUZHmrNzsjpwLe3H4onDj6m3hKCmYRu7JIP5pNLecaw2lggcS","crv":"P-384","d":"1zK95W1S7WgHd62sr7MsN8mwmMgsVtj4jBGYgtnvMHAY7iiWUSIdtyjmCfgHGML_"}'
      - RECEIVER_KEY ='{"kty":"EC","kid":"918f5a24-290e-4659-9cd6-c8d95aee92c6","x":"Sw9dXf0VErH_kaP7wWqsy1Iy4ahIwRDWKBG4sHtl-2Rmy4NrFpttFAK2Akcj__Gg","y":"TJAzD-yQqdvNyFTpkm6f-NC_QIz71MSeeMWOcYwKC-SBkmsI4ixNCmK6LSefq7Gs","crv":"P-384","d":"vGy3w59unwLxuWSE82ApKgJmmOSDfb-5jUQ-bRwx-7-3VXE43a0t1RJtyp8XwcZe"}'
jobs:
  include:
    - jdk: oraclejdk10
      env: DATABASE_URL='jdbc:mysql://localhost/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='root'
      script: sudo docker run -d --name mysqlserver -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=external_storage mysql:8
    - jdk: openjdk10
      env: DATABASE_URL='jdbc:mysql://localhost/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='root'
      script: sudo docker run -d --name mysqlserver -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=external_storage mysql:8
    - jdk: oraclejdk10
      env: DATABASE_URL='jdbc:sqlserver://localhost;database=external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='Password45'
      script:
        - sudo docker run --name sqlserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password45' -e MSSQL_PID=Developer -p 1433:1433 -d microsoft/mssql-server-linux:latest
        - sudo docker exec -it sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password45' -Q 'create database external_storage'
    - jdk: openjdk10
      env: DATABASE_URL='jdbc:sqlserver://localhost;database=external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='Password45'
      script:
        - sudo docker run --name sqlserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password45' -e MSSQL_PID=Developer -p 1433:1433 -d microsoft/mssql-server-linux:latest
        - sudo docker exec -it sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password45' -Q 'create database external_storage'
    - jdk: oraclejdk10
      env: DATABASE_URL='jdbc:postgresql://localhost:5433/external_storage' DATABASE_USERNAME='postgres' DATABASE_PASSWORD='postgres'
      script: sudo docker run --name postgresserver -p 5433:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=external_storage -d postgres:9.6
    - jdk: openjdk10
      env: DATABASE_URL='jdbc:postgresql://localhost:5433/external_storage' DATABASE_USERNAME='postgres' DATABASE_PASSWORD='postgres'
      script: sudo docker run --name postgresserver -p 5433:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=external_storage -d postgres:9.6
cache:
  directories:
    - "$HOME/.m2"
