language: java
jdk:
  - oraclejdk10
  - openjdk10
services:
  - docker
before_install:
 - sudo service mysql stop
env:
  matrix:
    - DATABASE_URL=$DATABASE_URL_POSTGRES DATABASE_PASSWORD=$DATABASE_PASSWORD_POSTGRES
jobs:
  include:
   - jdk: oraclejdk10
     env: DATABASE_URL='jdbc:mysql://localhost/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='root'
     script: sudo docker run -d --name mysqlserver -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=external_storage mysql:8
   - jdk: openjdk10
     env: DATABASE_URL='jdbc:mysql://localhost/external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='root'
     script: sudo docker run -d --name mysqlserver -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=external_storage mysql:8
   - jdk: oraclejdk10
     env: DATABASE_URL='jdbc:sqlserver://localhost;database=external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='Password45'
     script:
      - sudo docker run --name sqlserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password45' -e MSSQL_PID=Developer -p 1433:1433 -d microsoft/mssql-server-linux:2017-CU8
      - sudo docker exec -it sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password45' -Q 'create database external_storage'
   - jdk: openjdk10
     env: DATABASE_URL='jdbc:sqlserver://localhost;database=external_storage' DATABASE_USERNAME='root' DATABASE_PASSWORD='Password45'
     script:
     - sudo docker run --name sqlserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password45' -e MSSQL_PID=Developer -p 1433:1433 -d microsoft/mssql-server-linux:2017-CU8
     - sudo docker exec -it sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password45' -Q 'create database external_storage'

cache:
  directories:
    - "$HOME/.m2"
