language: java
jdk:
  - oraclejdk10
  - openjdk10
  - oraclejdk11
  - openjdk11
env:
  matrix:
    - DATABASE_URL=$DATABASE_URL_POSTGRES DATABASE_PASSWORD=$DATABASE_PASSWORD_POSTGRES
    - DATABASE_URL=$DATABASE_URL_MYSQL DATABASE_PASSWORD=$DATABASE_PASSWORD_MYSQL
    - DATABASE_URL=$DATABASE_URL_MSSQL DATABASE_PASSWORD=$DATABASE_PASSWORD_MSSQL
cache:
  directories:
    - "$HOME/.m2"
